extensions:
  headers_setter:
    headers:
      - action: upsert
        key: x-oneuptime-service-token
        from_context: x-oneuptime-service-token

processors:

receivers:
  otlp:
    protocols:
      grpc:
        include_metadata: true
      http:
        include_metadata: true



exporters:
  otlphttp:
    endpoint: "http://${env:SERVER_INGESTOR_HOSTNAME}:${env:INGESTOR_PORT}/otlp"
    headers: {"Content-Type": "application/json"}
    auth:
      authenticator: headers_setter

service:
  telemetry:
    logs:
      level: "debug"
  extensions: [ headers_setter ]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]